apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
  labels:
    app: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
      tier: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: springboot-app
        tier: backend
    spec:
      containers:
      - name: springboot-app
        image: jamlhet/gs-spring-boot-docker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10080
