apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring-slave
  labels:
    app: springApp
spec:
  selector:
    matchLabels:
      app: springApp
      role: slave
      tier: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: springApp
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: jamlhet/gs-spring-boot-docker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 10080