apiVersion: v1
kind: Service
metadata:
  name: spring-slave
  labels:
    app: springApp
    role: slave
    tier: backend
spec:
  ports:
  - port: 10080
  selector:
    app: springApp
    role: slave
    tier: backend