apiVersion: apps/v1
kind: Deployment
metadata:
  name: juank-deployment
  labels:
    app: juank-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: juank-app
      tier: backend
  template:
    metadata:
      labels:
        app: juank-app
        tier: backend
    spec:
      containers:
      - name: juank-app
        image: jamlhet/gs-spring-boot-docker
        ports:
        - containerPort: 10080
