apiVersion: apps/v1
kind: Deployment
metadata:
  name: juank-test-deployment
  labels:
    app: juank-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: juank-test
  template:
    metadata:
      labels:
        app: juank-test
    spec:
      containers:
        name: juank-test
        image: jamlhet/gs-spring-boot-docker
        ports:
          containerPort: 10080
