apiVersion: v1
kind: Service
metadata:
  name: spring-master
  labels:
    app: springApp
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 10080
  selector:
    app: springApp
    role: master
    tier: backend