apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  labels:
    app: springboot-app
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 10080
  selector:
    app: role: master
    tier: backend
