apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-master
  labels:
    app: springApp
spec:
  selector:
    matchLabels:
      app: springApp
      tier: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: springApp
        tier: backend
    spec:
      containers:
      - name: springApp
        image: jamlhet/gs-spring-boot-docker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10080